### ISSUE TITLE
for引用参数示例代码错误

### ISSUE THREAD

**Issue by yougg** [duanbiaowu/go-examples-for-beginners#12]
https://github.com/duanbiaowu/go-examples-for-beginners/blob/26ecde2fbaffd9a26f14a8d7359fc97fdda5ffee/performance/for.md?plain=1#L79

这里根据题意for的第二种方式应该是 `for _, person := range persons {`

**Comment by duanbiaowu** [comment]
> https://github.com/duanbiaowu/go-examples-for-beginners/blob/26ecde2fbaffd9a26f14a8d7359fc97fdda5ffee/performance/for.md?plain=1#L79
> 
> 这里根据题意for的第二种方式应该是 `for _, person := range persons {`

这是初始化数据的，对基准测试无影响，你看下上下文代码。
